version: "3.4"

services:

  mongo:
    image: mongo
    container_name: recapidb.git
    restart: unless-stopped
    environment:
      - "TZ=Europe/Stockholm"
    volumes:
      - ./db/data:/data/db
      - ./db/config:/data/configdb

  recapi: 
    container_name: recapi.git
    image: odtdock/recapi
    depends_on:
      - mongo
    restart: unless-stopped
    build: .
    volumes:
      - ./config.yml:/app/config.yml
      - /data/rec:/data/rec
    ports:
      - "23040:23040"
    environment:
      - "TZ=Europe/Stockholm"
