version: "3.4"

services:

  mongo.git:
    image: mongo
    container_name: recapidb.git
    restart: always
    environment:
      - "TZ=Europe/Stockholm"
    volumes:
      - ./db/data:/data/db
      - ./db/config:/data/configdb

  recapi.git: 
    image: recapi.git
    container_name: recapi.git
    depends_on:
      - recapidb.git
    restart: always
    build: .
    volumes:
      - ./config.yml:/app/config.yml
      - /data/rec:/data/rec
    ports:
      - "23040:23040"
    environment:
      - "TZ=Europe/Stockholm"
