version: "3.4"

services:
  recapi: 
    container_name: recapi
    depends_on:
      - mongo
    restart: always
    build: .
    volumes:
      - /glust/docker/recapi/config.yml:/app/config.yml
      - /data/rec:/rec
    ports:
      - "23030:23030"
    environment:
      - "TZ=Europe/Stockholm"

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - "TZ=Europe/Stockholm"
    volumes:
      - /glust/docker/mongo/data:/data/db

