version: "3.4"

services:

  mongo.git:
    image: mongo
    container_name: mongo.git
    restart: always
    environment:
      - "TZ=Europe/Stockholm"
    volumes:
      - ./datadb:/data/db
      - ./configdb:/data/configdb

  recapi.git: 
    container_name: recapi.git
    depends_on:
      - mongo.git
    restart: always
    build: .
    volumes:
      - ./config.yml:/app/config.yml
      - /data/rec:/data/rec
    ports:
      - "23040:23040"
    environment:
      - "TZ=Europe/Stockholm"
